/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PaginatedPortfolioProjects {
  'total' : bigint,
  'items' : Array<PortfolioProject>,
}
export type PortfolioCategory = { 'ai' : null } |
  { 'web' : null } |
  { 'saas' : null } |
  { 'blockchain' : null } |
  { 'mobile' : null } |
  { 'branding' : null };
export interface PortfolioFilter {
  'status' : [] | [PublishStatus],
  'search' : [] | [string],
  'category' : [] | [PortfolioCategory],
}
export interface PortfolioProject {
  'id' : bigint,
  'galleryImages' : Array<ExternalBlob>,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'clientName' : string,
  'displayOrder' : bigint,
  'technologiesUsed' : Array<string>,
  'tags' : Array<string>,
  'createdDate' : [] | [bigint],
  'publishStatus' : PublishStatus,
  'description' : string,
  'results' : Array<string>,
  'linkedTestimonialId' : [] | [bigint],
  'category' : PortfolioCategory,
  'lastUpdatedDate' : [] | [bigint],
  'industry' : string,
}
export interface PortfolioProjectInput {
  'galleryImages' : Array<ExternalBlob>,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'clientName' : string,
  'displayOrder' : bigint,
  'technologiesUsed' : Array<string>,
  'tags' : Array<string>,
  'publishStatus' : PublishStatus,
  'description' : string,
  'results' : Array<string>,
  'linkedTestimonialId' : [] | [bigint],
  'category' : PortfolioCategory,
  'industry' : string,
}
export interface PortfolioProjectUpdate {
  'id' : bigint,
  'galleryImages' : Array<ExternalBlob>,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'clientName' : string,
  'displayOrder' : bigint,
  'technologiesUsed' : Array<string>,
  'tags' : Array<string>,
  'publishStatus' : PublishStatus,
  'description' : string,
  'results' : Array<string>,
  'linkedTestimonialId' : [] | [bigint],
  'category' : PortfolioCategory,
  'industry' : string,
}
export type PublishStatus = { 'published' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface Testimonial {
  'id' : bigint,
  'quote' : string,
  'authorName' : string,
  'jobTitle' : string,
  'companyName' : string,
  'photo' : [] | [ExternalBlob],
  'linkedPortfolioId' : [] | [bigint],
  'rating' : bigint,
  'displayOrder' : bigint,
  'isVisible' : boolean,
  'createdDate' : [] | [bigint],
  'lastUpdatedDate' : [] | [bigint],
}
export interface TestimonialInput {
  'quote' : string,
  'authorName' : string,
  'jobTitle' : string,
  'companyName' : string,
  'photo' : [] | [ExternalBlob],
  'linkedPortfolioId' : [] | [bigint],
  'rating' : bigint,
  'displayOrder' : bigint,
  'isVisible' : boolean,
}
export interface TestimonialUpdate {
  'id' : bigint,
  'quote' : string,
  'authorName' : string,
  'jobTitle' : string,
  'companyName' : string,
  'photo' : [] | [ExternalBlob],
  'linkedPortfolioId' : [] | [bigint],
  'rating' : bigint,
  'displayOrder' : bigint,
  'isVisible' : boolean,
}
export interface TestimonialFilter {
  'isVisible' : [] | [boolean],
  'minRating' : [] | [bigint],
  'maxRating' : [] | [bigint],
  'search' : [] | [string],
}
export interface PaginatedTestimonials {
  'total' : bigint,
  'items' : Array<Testimonial>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeletePortfolioProjects' : ActorMethod<[Array<bigint>], bigint>,
  'bulkUpdatePortfolioStatus' : ActorMethod<
    [Array<bigint>, PublishStatus],
    bigint
  >,
  'createPortfolioProject' : ActorMethod<
    [PortfolioProjectInput],
    PortfolioProject
  >,
  'deletePortfolioProject' : ActorMethod<[bigint], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioProject' : ActorMethod<[bigint], [] | [PortfolioProject]>,
  'getPortfolioProjects' : ActorMethod<
    [bigint, bigint, [] | [PortfolioFilter]],
    PaginatedPortfolioProjects
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderPortfolioProjects' : ActorMethod<[Array<bigint>], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePortfolioProject' : ActorMethod<
    [PortfolioProjectUpdate],
    [] | [PortfolioProject]
  >,
  'bulkDeleteTestimonials' : ActorMethod<[Array<bigint>], bigint>,
  'bulkUpdateTestimonialVisibility' : ActorMethod<[Array<bigint>, boolean], bigint>,
  'createTestimonial' : ActorMethod<[TestimonialInput], Testimonial>,
  'deleteTestimonial' : ActorMethod<[bigint], boolean>,
  'getTestimonial' : ActorMethod<[bigint], [] | [Testimonial]>,
  'getTestimonials' : ActorMethod<
    [bigint, bigint, [] | [TestimonialFilter]],
    PaginatedTestimonials
  >,
  'reorderTestimonials' : ActorMethod<[Array<bigint>], boolean>,
  'updateTestimonial' : ActorMethod<[TestimonialUpdate], [] | [Testimonial]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
