/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublishStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PortfolioCategory = IDL.Variant({
  'ai' : IDL.Null,
  'web' : IDL.Null,
  'saas' : IDL.Null,
  'blockchain' : IDL.Null,
  'mobile' : IDL.Null,
  'branding' : IDL.Null,
});
export const PortfolioProjectInput = IDL.Record({
  'galleryImages' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'technologiesUsed' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'publishStatus' : PublishStatus,
  'description' : IDL.Text,
  'results' : IDL.Vec(IDL.Text),
  'linkedTestimonialId' : IDL.Opt(IDL.Nat),
  'category' : PortfolioCategory,
  'projectUrl' : IDL.Opt(IDL.Text),
  'industry' : IDL.Text,
});
export const PortfolioProject = IDL.Record({
  'id' : IDL.Nat,
  'galleryImages' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'technologiesUsed' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'createdDate' : IDL.Opt(IDL.Int),
  'publishStatus' : PublishStatus,
  'description' : IDL.Text,
  'results' : IDL.Vec(IDL.Text),
  'linkedTestimonialId' : IDL.Opt(IDL.Nat),
  'category' : PortfolioCategory,
  'lastUpdatedDate' : IDL.Opt(IDL.Int),
  'projectUrl' : IDL.Opt(IDL.Text),
  'industry' : IDL.Text,
});
export const ServiceFaq = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const ServiceProcessStep = IDL.Record({
  'step' : IDL.Text,
  'description' : IDL.Text,
});
export const ServiceInput = IDL.Record({
  'useCases' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'faqs' : IDL.Vec(ServiceFaq),
  'icon' : IDL.Opt(ExternalBlob),
  'processSteps' : IDL.Vec(ServiceProcessStep),
  'targetAudience' : IDL.Text,
  'shortDescription' : IDL.Text,
  'isVisible' : IDL.Bool,
  'fullDescription' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'useCases' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'faqs' : IDL.Vec(ServiceFaq),
  'icon' : IDL.Opt(ExternalBlob),
  'createdDate' : IDL.Opt(IDL.Int),
  'processSteps' : IDL.Vec(ServiceProcessStep),
  'targetAudience' : IDL.Text,
  'shortDescription' : IDL.Text,
  'isVisible' : IDL.Bool,
  'lastUpdatedDate' : IDL.Opt(IDL.Int),
  'fullDescription' : IDL.Text,
});
export const TestimonialInput = IDL.Record({
  'displayOrder' : IDL.Nat,
  'authorName' : IDL.Text,
  'quote' : IDL.Text,
  'linkedPortfolioId' : IDL.Opt(IDL.Nat),
  'jobTitle' : IDL.Text,
  'isVisible' : IDL.Bool,
  'companyName' : IDL.Text,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'authorName' : IDL.Text,
  'createdDate' : IDL.Opt(IDL.Int),
  'quote' : IDL.Text,
  'linkedPortfolioId' : IDL.Opt(IDL.Nat),
  'jobTitle' : IDL.Text,
  'isVisible' : IDL.Bool,
  'companyName' : IDL.Text,
  'lastUpdatedDate' : IDL.Opt(IDL.Int),
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});
export const ExportTotalRecords = IDL.Record({
  'portfolio' : IDL.Nat,
  'testimonials' : IDL.Nat,
  'services' : IDL.Nat,
});
export const ExportMetadata = IDL.Record({
  'exportVersion' : IDL.Text,
  'exportDate' : IDL.Int,
  'totalRecords' : ExportTotalRecords,
});
export const ContactMap = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ContactWhatsApp = IDL.Record({
  'isEnabled' : IDL.Bool,
  'number' : IDL.Opt(IDL.Text),
});
export const ContactEmail = IDL.Record({
  'secondary' : IDL.Opt(IDL.Text),
  'primary' : IDL.Text,
  'responseTime' : IDL.Text,
});
export const BusinessHours = IDL.Record({
  'tuesday' : IDL.Text,
  'wednesday' : IDL.Text,
  'saturday' : IDL.Text,
  'thursday' : IDL.Text,
  'sunday' : IDL.Text,
  'friday' : IDL.Text,
  'monday' : IDL.Text,
});
export const ContactAddress = IDL.Record({
  'businessHours' : BusinessHours,
  'fullAddress' : IDL.Text,
});
export const ContactPhone = IDL.Record({
  'secondary' : IDL.Opt(IDL.Text),
  'isEnabled' : IDL.Bool,
  'primary' : IDL.Opt(IDL.Text),
});
export const ContactSettings = IDL.Record({
  'map' : ContactMap,
  'lastUpdated' : IDL.Int,
  'whatsapp' : ContactWhatsApp,
  'email' : ContactEmail,
  'address' : ContactAddress,
  'phone' : ContactPhone,
});
export const ExportData = IDL.Record({
  'portfolio' : IDL.Vec(PortfolioProject),
  'metadata' : ExportMetadata,
  'testimonials' : IDL.Vec(Testimonial),
  'services' : IDL.Vec(Service),
  'contactSettings' : IDL.Opt(ContactSettings),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HomepageData = IDL.Record({
  'featuredProjects' : IDL.Vec(PortfolioProject),
  'testimonials' : IDL.Vec(Testimonial),
  'services' : IDL.Vec(Service),
});
export const PortfolioFilter = IDL.Record({
  'status' : IDL.Opt(PublishStatus),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(PortfolioCategory),
});
export const PaginatedPortfolioProjects = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(PortfolioProject),
});
export const ServiceFilter = IDL.Record({
  'search' : IDL.Opt(IDL.Text),
  'isVisible' : IDL.Opt(IDL.Bool),
});
export const PaginatedServices = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(Service),
});
export const TestimonialFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Nat),
  'search' : IDL.Opt(IDL.Text),
  'isVisible' : IDL.Opt(IDL.Bool),
  'maxRating' : IDL.Opt(IDL.Nat),
});
export const PaginatedTestimonials = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(Testimonial),
});
export const ImportMode = IDL.Variant({
  'createAndUpdate' : IDL.Null,
  'skip' : IDL.Null,
  'createOnly' : IDL.Null,
  'replaceAll' : IDL.Null,
});
export const ImportOptions = IDL.Record({
  'portfolioMode' : ImportMode,
  'importContactSettings' : IDL.Bool,
  'servicesMode' : ImportMode,
  'testimonialsMode' : ImportMode,
});
export const ImportResultCounts = IDL.Record({
  'created' : IDL.Nat,
  'updated' : IDL.Nat,
});
export const ImportResult = IDL.Record({
  'portfolio' : ImportResultCounts,
  'contactSettingsUpdated' : IDL.Bool,
  'testimonials' : ImportResultCounts,
  'services' : ImportResultCounts,
});
export const PortfolioProjectUpdate = IDL.Record({
  'id' : IDL.Nat,
  'galleryImages' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'technologiesUsed' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'publishStatus' : PublishStatus,
  'description' : IDL.Text,
  'results' : IDL.Vec(IDL.Text),
  'linkedTestimonialId' : IDL.Opt(IDL.Nat),
  'category' : PortfolioCategory,
  'projectUrl' : IDL.Opt(IDL.Text),
  'industry' : IDL.Text,
});
export const ServiceUpdate = IDL.Record({
  'id' : IDL.Nat,
  'useCases' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'faqs' : IDL.Vec(ServiceFaq),
  'icon' : IDL.Opt(ExternalBlob),
  'processSteps' : IDL.Vec(ServiceProcessStep),
  'targetAudience' : IDL.Text,
  'shortDescription' : IDL.Text,
  'isVisible' : IDL.Bool,
  'fullDescription' : IDL.Text,
});
export const TestimonialUpdate = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'authorName' : IDL.Text,
  'quote' : IDL.Text,
  'linkedPortfolioId' : IDL.Opt(IDL.Nat),
  'jobTitle' : IDL.Text,
  'isVisible' : IDL.Bool,
  'companyName' : IDL.Text,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkDeletePortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'bulkDeleteServices' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'bulkDeleteTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'bulkUpdatePortfolioStatus' : IDL.Func(
      [IDL.Vec(IDL.Nat), PublishStatus],
      [IDL.Nat],
      [],
    ),
  'bulkUpdateServiceVisibility' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'bulkUpdateTestimonialVisibility' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPortfolioProject' : IDL.Func(
      [PortfolioProjectInput],
      [PortfolioProject],
      [],
    ),
  'createService' : IDL.Func([ServiceInput], [Service], []),
  'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
  'deletePortfolioProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'exportData' : IDL.Func([], [ExportData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSettings' : IDL.Func([], [ContactSettings], ['query']),
  'getHomepageData' : IDL.Func([], [HomepageData], ['query']),
  'getPortfolioProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PortfolioProject)],
      ['query'],
    ),
  'getPortfolioProjects' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(PortfolioFilter)],
      [PaginatedPortfolioProjects],
      ['query'],
    ),
  'getPreviousContactSettings' : IDL.Func(
      [],
      [IDL.Opt(ContactSettings)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getServices' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(ServiceFilter)],
      [PaginatedServices],
      ['query'],
    ),
  'getTestimonial' : IDL.Func([IDL.Nat], [IDL.Opt(Testimonial)], ['query']),
  'getTestimonials' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(TestimonialFilter)],
      [PaginatedTestimonials],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importData' : IDL.Func([ExportData, ImportOptions], [ImportResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderPortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'reorderServices' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'reorderTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'resetContactSettings' : IDL.Func([], [ContactSettings], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContactSettings' : IDL.Func([ContactSettings], [ContactSettings], []),
  'updatePortfolioProject' : IDL.Func(
      [PortfolioProjectUpdate],
      [IDL.Opt(PortfolioProject)],
      [],
    ),
  'updateService' : IDL.Func([ServiceUpdate], [IDL.Opt(Service)], []),
  'updateTestimonial' : IDL.Func(
      [TestimonialUpdate],
      [IDL.Opt(Testimonial)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublishStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PortfolioCategory = IDL.Variant({
    'ai' : IDL.Null,
    'web' : IDL.Null,
    'saas' : IDL.Null,
    'blockchain' : IDL.Null,
    'mobile' : IDL.Null,
    'branding' : IDL.Null,
  });
  const PortfolioProjectInput = IDL.Record({
    'galleryImages' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'technologiesUsed' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'publishStatus' : PublishStatus,
    'description' : IDL.Text,
    'results' : IDL.Vec(IDL.Text),
    'linkedTestimonialId' : IDL.Opt(IDL.Nat),
    'category' : PortfolioCategory,
    'projectUrl' : IDL.Opt(IDL.Text),
    'industry' : IDL.Text,
  });
  const PortfolioProject = IDL.Record({
    'id' : IDL.Nat,
    'galleryImages' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'technologiesUsed' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'createdDate' : IDL.Opt(IDL.Int),
    'publishStatus' : PublishStatus,
    'description' : IDL.Text,
    'results' : IDL.Vec(IDL.Text),
    'linkedTestimonialId' : IDL.Opt(IDL.Nat),
    'category' : PortfolioCategory,
    'lastUpdatedDate' : IDL.Opt(IDL.Int),
    'projectUrl' : IDL.Opt(IDL.Text),
    'industry' : IDL.Text,
  });
  const ServiceFaq = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const ServiceProcessStep = IDL.Record({
    'step' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServiceInput = IDL.Record({
    'useCases' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'faqs' : IDL.Vec(ServiceFaq),
    'icon' : IDL.Opt(ExternalBlob),
    'processSteps' : IDL.Vec(ServiceProcessStep),
    'targetAudience' : IDL.Text,
    'shortDescription' : IDL.Text,
    'isVisible' : IDL.Bool,
    'fullDescription' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'useCases' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'faqs' : IDL.Vec(ServiceFaq),
    'icon' : IDL.Opt(ExternalBlob),
    'createdDate' : IDL.Opt(IDL.Int),
    'processSteps' : IDL.Vec(ServiceProcessStep),
    'targetAudience' : IDL.Text,
    'shortDescription' : IDL.Text,
    'isVisible' : IDL.Bool,
    'lastUpdatedDate' : IDL.Opt(IDL.Int),
    'fullDescription' : IDL.Text,
  });
  const TestimonialInput = IDL.Record({
    'displayOrder' : IDL.Nat,
    'authorName' : IDL.Text,
    'quote' : IDL.Text,
    'linkedPortfolioId' : IDL.Opt(IDL.Nat),
    'jobTitle' : IDL.Text,
    'isVisible' : IDL.Bool,
    'companyName' : IDL.Text,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'authorName' : IDL.Text,
    'createdDate' : IDL.Opt(IDL.Int),
    'quote' : IDL.Text,
    'linkedPortfolioId' : IDL.Opt(IDL.Nat),
    'jobTitle' : IDL.Text,
    'isVisible' : IDL.Bool,
    'companyName' : IDL.Text,
    'lastUpdatedDate' : IDL.Opt(IDL.Int),
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const ExportTotalRecords = IDL.Record({
    'portfolio' : IDL.Nat,
    'testimonials' : IDL.Nat,
    'services' : IDL.Nat,
  });
  const ExportMetadata = IDL.Record({
    'exportVersion' : IDL.Text,
    'exportDate' : IDL.Int,
    'totalRecords' : ExportTotalRecords,
  });
  const ContactMap = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ContactWhatsApp = IDL.Record({
    'isEnabled' : IDL.Bool,
    'number' : IDL.Opt(IDL.Text),
  });
  const ContactEmail = IDL.Record({
    'secondary' : IDL.Opt(IDL.Text),
    'primary' : IDL.Text,
    'responseTime' : IDL.Text,
  });
  const BusinessHours = IDL.Record({
    'tuesday' : IDL.Text,
    'wednesday' : IDL.Text,
    'saturday' : IDL.Text,
    'thursday' : IDL.Text,
    'sunday' : IDL.Text,
    'friday' : IDL.Text,
    'monday' : IDL.Text,
  });
  const ContactAddress = IDL.Record({
    'businessHours' : BusinessHours,
    'fullAddress' : IDL.Text,
  });
  const ContactPhone = IDL.Record({
    'secondary' : IDL.Opt(IDL.Text),
    'isEnabled' : IDL.Bool,
    'primary' : IDL.Opt(IDL.Text),
  });
  const ContactSettings = IDL.Record({
    'map' : ContactMap,
    'lastUpdated' : IDL.Int,
    'whatsapp' : ContactWhatsApp,
    'email' : ContactEmail,
    'address' : ContactAddress,
    'phone' : ContactPhone,
  });
  const ExportData = IDL.Record({
    'portfolio' : IDL.Vec(PortfolioProject),
    'metadata' : ExportMetadata,
    'testimonials' : IDL.Vec(Testimonial),
    'services' : IDL.Vec(Service),
    'contactSettings' : IDL.Opt(ContactSettings),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HomepageData = IDL.Record({
    'featuredProjects' : IDL.Vec(PortfolioProject),
    'testimonials' : IDL.Vec(Testimonial),
    'services' : IDL.Vec(Service),
  });
  const PortfolioFilter = IDL.Record({
    'status' : IDL.Opt(PublishStatus),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(PortfolioCategory),
  });
  const PaginatedPortfolioProjects = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(PortfolioProject),
  });
  const ServiceFilter = IDL.Record({
    'search' : IDL.Opt(IDL.Text),
    'isVisible' : IDL.Opt(IDL.Bool),
  });
  const PaginatedServices = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(Service),
  });
  const TestimonialFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Nat),
    'search' : IDL.Opt(IDL.Text),
    'isVisible' : IDL.Opt(IDL.Bool),
    'maxRating' : IDL.Opt(IDL.Nat),
  });
  const PaginatedTestimonials = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(Testimonial),
  });
  const ImportMode = IDL.Variant({
    'createAndUpdate' : IDL.Null,
    'skip' : IDL.Null,
    'createOnly' : IDL.Null,
    'replaceAll' : IDL.Null,
  });
  const ImportOptions = IDL.Record({
    'portfolioMode' : ImportMode,
    'importContactSettings' : IDL.Bool,
    'servicesMode' : ImportMode,
    'testimonialsMode' : ImportMode,
  });
  const ImportResultCounts = IDL.Record({
    'created' : IDL.Nat,
    'updated' : IDL.Nat,
  });
  const ImportResult = IDL.Record({
    'portfolio' : ImportResultCounts,
    'contactSettingsUpdated' : IDL.Bool,
    'testimonials' : ImportResultCounts,
    'services' : ImportResultCounts,
  });
  const PortfolioProjectUpdate = IDL.Record({
    'id' : IDL.Nat,
    'galleryImages' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'technologiesUsed' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'publishStatus' : PublishStatus,
    'description' : IDL.Text,
    'results' : IDL.Vec(IDL.Text),
    'linkedTestimonialId' : IDL.Opt(IDL.Nat),
    'category' : PortfolioCategory,
    'projectUrl' : IDL.Opt(IDL.Text),
    'industry' : IDL.Text,
  });
  const ServiceUpdate = IDL.Record({
    'id' : IDL.Nat,
    'useCases' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'faqs' : IDL.Vec(ServiceFaq),
    'icon' : IDL.Opt(ExternalBlob),
    'processSteps' : IDL.Vec(ServiceProcessStep),
    'targetAudience' : IDL.Text,
    'shortDescription' : IDL.Text,
    'isVisible' : IDL.Bool,
    'fullDescription' : IDL.Text,
  });
  const TestimonialUpdate = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'authorName' : IDL.Text,
    'quote' : IDL.Text,
    'linkedPortfolioId' : IDL.Opt(IDL.Nat),
    'jobTitle' : IDL.Text,
    'isVisible' : IDL.Bool,
    'companyName' : IDL.Text,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkDeletePortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'bulkDeleteServices' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'bulkDeleteTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'bulkUpdatePortfolioStatus' : IDL.Func(
        [IDL.Vec(IDL.Nat), PublishStatus],
        [IDL.Nat],
        [],
      ),
    'bulkUpdateServiceVisibility' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'bulkUpdateTestimonialVisibility' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createPortfolioProject' : IDL.Func(
        [PortfolioProjectInput],
        [PortfolioProject],
        [],
      ),
    'createService' : IDL.Func([ServiceInput], [Service], []),
    'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
    'deletePortfolioProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'exportData' : IDL.Func([], [ExportData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSettings' : IDL.Func([], [ContactSettings], ['query']),
    'getHomepageData' : IDL.Func([], [HomepageData], ['query']),
    'getPortfolioProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioProject)],
        ['query'],
      ),
    'getPortfolioProjects' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(PortfolioFilter)],
        [PaginatedPortfolioProjects],
        ['query'],
      ),
    'getPreviousContactSettings' : IDL.Func(
        [],
        [IDL.Opt(ContactSettings)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getServices' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(ServiceFilter)],
        [PaginatedServices],
        ['query'],
      ),
    'getTestimonial' : IDL.Func([IDL.Nat], [IDL.Opt(Testimonial)], ['query']),
    'getTestimonials' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(TestimonialFilter)],
        [PaginatedTestimonials],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importData' : IDL.Func([ExportData, ImportOptions], [ImportResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderPortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'reorderServices' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'reorderTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'resetContactSettings' : IDL.Func([], [ContactSettings], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContactSettings' : IDL.Func(
        [ContactSettings],
        [ContactSettings],
        [],
      ),
    'updatePortfolioProject' : IDL.Func(
        [PortfolioProjectUpdate],
        [IDL.Opt(PortfolioProject)],
        [],
      ),
    'updateService' : IDL.Func([ServiceUpdate], [IDL.Opt(Service)], []),
    'updateTestimonial' : IDL.Func(
        [TestimonialUpdate],
        [IDL.Opt(Testimonial)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };