/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublishStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PortfolioCategory = IDL.Variant({
  'ai' : IDL.Null,
  'web' : IDL.Null,
  'saas' : IDL.Null,
  'blockchain' : IDL.Null,
  'mobile' : IDL.Null,
  'branding' : IDL.Null,
});
export const PortfolioProjectInput = IDL.Record({
  'galleryImages' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'technologiesUsed' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'publishStatus' : PublishStatus,
  'description' : IDL.Text,
  'results' : IDL.Vec(IDL.Text),
  'linkedTestimonialId' : IDL.Opt(IDL.Nat),
  'category' : PortfolioCategory,
  'industry' : IDL.Text,
});
export const PortfolioProject = IDL.Record({
  'id' : IDL.Nat,
  'galleryImages' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'technologiesUsed' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'createdDate' : IDL.Opt(IDL.Int),
  'publishStatus' : PublishStatus,
  'description' : IDL.Text,
  'results' : IDL.Vec(IDL.Text),
  'linkedTestimonialId' : IDL.Opt(IDL.Nat),
  'category' : PortfolioCategory,
  'lastUpdatedDate' : IDL.Opt(IDL.Int),
  'industry' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PortfolioFilter = IDL.Record({
  'status' : IDL.Opt(PublishStatus),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(PortfolioCategory),
});
export const PaginatedPortfolioProjects = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(PortfolioProject),
});
export const PortfolioProjectUpdate = IDL.Record({
  'id' : IDL.Nat,
  'galleryImages' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'clientName' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'technologiesUsed' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'publishStatus' : PublishStatus,
  'description' : IDL.Text,
  'results' : IDL.Vec(IDL.Text),
  'linkedTestimonialId' : IDL.Opt(IDL.Nat),
  'category' : PortfolioCategory,
  'industry' : IDL.Text,
});
export const TestimonialInput = IDL.Record({
  'quote' : IDL.Text,
  'authorName' : IDL.Text,
  'jobTitle' : IDL.Text,
  'companyName' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'linkedPortfolioId' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'isVisible' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'quote' : IDL.Text,
  'authorName' : IDL.Text,
  'jobTitle' : IDL.Text,
  'companyName' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'linkedPortfolioId' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'isVisible' : IDL.Bool,
  'createdDate' : IDL.Opt(IDL.Int),
  'lastUpdatedDate' : IDL.Opt(IDL.Int),
});
export const TestimonialFilter = IDL.Record({
  'isVisible' : IDL.Opt(IDL.Bool),
  'minRating' : IDL.Opt(IDL.Nat),
  'maxRating' : IDL.Opt(IDL.Nat),
  'search' : IDL.Opt(IDL.Text),
});
export const PaginatedTestimonials = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(Testimonial),
});
export const TestimonialUpdate = IDL.Record({
  'id' : IDL.Nat,
  'quote' : IDL.Text,
  'authorName' : IDL.Text,
  'jobTitle' : IDL.Text,
  'companyName' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'linkedPortfolioId' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'isVisible' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkDeletePortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'bulkUpdatePortfolioStatus' : IDL.Func(
      [IDL.Vec(IDL.Nat), PublishStatus],
      [IDL.Nat],
      [],
    ),
  'createPortfolioProject' : IDL.Func(
      [PortfolioProjectInput],
      [PortfolioProject],
      [],
    ),
  'deletePortfolioProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioProject' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PortfolioProject)],
      ['query'],
    ),
  'getPortfolioProjects' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(PortfolioFilter)],
      [PaginatedPortfolioProjects],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderPortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePortfolioProject' : IDL.Func(
      [PortfolioProjectUpdate],
      [IDL.Opt(PortfolioProject)],
      [],
    ),
  'bulkDeleteTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'bulkUpdateTestimonialVisibility' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getTestimonial' : IDL.Func([IDL.Nat], [IDL.Opt(Testimonial)], ['query']),
  'getTestimonials' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(TestimonialFilter)],
      [PaginatedTestimonials],
      ['query'],
    ),
  'reorderTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'updateTestimonial' : IDL.Func(
      [TestimonialUpdate],
      [IDL.Opt(Testimonial)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublishStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PortfolioCategory = IDL.Variant({
    'ai' : IDL.Null,
    'web' : IDL.Null,
    'saas' : IDL.Null,
    'blockchain' : IDL.Null,
    'mobile' : IDL.Null,
    'branding' : IDL.Null,
  });
  const PortfolioProjectInput = IDL.Record({
    'galleryImages' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'technologiesUsed' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'publishStatus' : PublishStatus,
    'description' : IDL.Text,
    'results' : IDL.Vec(IDL.Text),
    'linkedTestimonialId' : IDL.Opt(IDL.Nat),
    'category' : PortfolioCategory,
    'industry' : IDL.Text,
  });
  const PortfolioProject = IDL.Record({
    'id' : IDL.Nat,
    'galleryImages' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'technologiesUsed' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'createdDate' : IDL.Opt(IDL.Int),
    'publishStatus' : PublishStatus,
    'description' : IDL.Text,
    'results' : IDL.Vec(IDL.Text),
    'linkedTestimonialId' : IDL.Opt(IDL.Nat),
    'category' : PortfolioCategory,
    'lastUpdatedDate' : IDL.Opt(IDL.Int),
    'industry' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PortfolioFilter = IDL.Record({
    'status' : IDL.Opt(PublishStatus),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(PortfolioCategory),
  });
  const PaginatedPortfolioProjects = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(PortfolioProject),
  });
  const PortfolioProjectUpdate = IDL.Record({
    'id' : IDL.Nat,
    'galleryImages' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'clientName' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'technologiesUsed' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'publishStatus' : PublishStatus,
    'description' : IDL.Text,
    'results' : IDL.Vec(IDL.Text),
    'linkedTestimonialId' : IDL.Opt(IDL.Nat),
    'category' : PortfolioCategory,
    'industry' : IDL.Text,
  });
  const TestimonialInput = IDL.Record({
    'quote' : IDL.Text,
    'authorName' : IDL.Text,
    'jobTitle' : IDL.Text,
    'companyName' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'linkedPortfolioId' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'isVisible' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'quote' : IDL.Text,
    'authorName' : IDL.Text,
    'jobTitle' : IDL.Text,
    'companyName' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'linkedPortfolioId' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'isVisible' : IDL.Bool,
    'createdDate' : IDL.Opt(IDL.Int),
    'lastUpdatedDate' : IDL.Opt(IDL.Int),
  });
  const TestimonialFilter = IDL.Record({
    'isVisible' : IDL.Opt(IDL.Bool),
    'minRating' : IDL.Opt(IDL.Nat),
    'maxRating' : IDL.Opt(IDL.Nat),
    'search' : IDL.Opt(IDL.Text),
  });
  const PaginatedTestimonials = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(Testimonial),
  });
  const TestimonialUpdate = IDL.Record({
    'id' : IDL.Nat,
    'quote' : IDL.Text,
    'authorName' : IDL.Text,
    'jobTitle' : IDL.Text,
    'companyName' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'linkedPortfolioId' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'isVisible' : IDL.Bool,
  });

  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkDeletePortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'bulkUpdatePortfolioStatus' : IDL.Func(
        [IDL.Vec(IDL.Nat), PublishStatus],
        [IDL.Nat],
        [],
      ),
    'createPortfolioProject' : IDL.Func(
        [PortfolioProjectInput],
        [PortfolioProject],
        [],
      ),
    'deletePortfolioProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioProject' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PortfolioProject)],
        ['query'],
      ),
    'getPortfolioProjects' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(PortfolioFilter)],
        [PaginatedPortfolioProjects],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderPortfolioProjects' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePortfolioProject' : IDL.Func(
        [PortfolioProjectUpdate],
        [IDL.Opt(PortfolioProject)],
        [],
      ),
    'bulkDeleteTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'bulkUpdateTestimonialVisibility' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getTestimonial' : IDL.Func([IDL.Nat], [IDL.Opt(Testimonial)], ['query']),
    'getTestimonials' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(TestimonialFilter)],
        [PaginatedTestimonials],
        ['query'],
      ),
    'reorderTestimonials' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'updateTestimonial' : IDL.Func(
        [TestimonialUpdate],
        [IDL.Opt(Testimonial)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
