/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessHours {
  'tuesday' : string,
  'wednesday' : string,
  'saturday' : string,
  'thursday' : string,
  'sunday' : string,
  'friday' : string,
  'monday' : string,
}
export interface ContactAddress {
  'businessHours' : BusinessHours,
  'fullAddress' : string,
}
export interface ContactEmail {
  'secondary' : [] | [string],
  'primary' : string,
  'responseTime' : string,
}
export interface ContactMap { 'latitude' : number, 'longitude' : number }
export interface ContactPhone {
  'secondary' : [] | [string],
  'isEnabled' : boolean,
  'primary' : [] | [string],
}
export interface ContactSettings {
  'map' : ContactMap,
  'lastUpdated' : bigint,
  'whatsapp' : ContactWhatsApp,
  'email' : ContactEmail,
  'address' : ContactAddress,
  'phone' : ContactPhone,
}
export interface ContactWhatsApp {
  'isEnabled' : boolean,
  'number' : [] | [string],
}
export interface ExportData {
  'portfolio' : Array<PortfolioProject>,
  'metadata' : ExportMetadata,
  'testimonials' : Array<Testimonial>,
  'services' : Array<Service>,
  'contactSettings' : [] | [ContactSettings],
}
export interface ExportMetadata {
  'exportVersion' : string,
  'exportDate' : bigint,
  'totalRecords' : ExportTotalRecords,
}
export interface ExportTotalRecords {
  'portfolio' : bigint,
  'testimonials' : bigint,
  'services' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface HomepageData {
  'featuredProjects' : Array<PortfolioProject>,
  'testimonials' : Array<Testimonial>,
  'services' : Array<Service>,
}
export type ImportMode = { 'createAndUpdate' : null } |
  { 'skip' : null } |
  { 'createOnly' : null } |
  { 'replaceAll' : null };
export interface ImportOptions {
  'portfolioMode' : ImportMode,
  'importContactSettings' : boolean,
  'servicesMode' : ImportMode,
  'testimonialsMode' : ImportMode,
}
export interface ImportResult {
  'portfolio' : ImportResultCounts,
  'contactSettingsUpdated' : boolean,
  'testimonials' : ImportResultCounts,
  'services' : ImportResultCounts,
}
export interface ImportResultCounts { 'created' : bigint, 'updated' : bigint }
export interface PaginatedPortfolioProjects {
  'total' : bigint,
  'items' : Array<PortfolioProject>,
}
export interface PaginatedServices {
  'total' : bigint,
  'items' : Array<Service>,
}
export interface PaginatedTestimonials {
  'total' : bigint,
  'items' : Array<Testimonial>,
}
export type PortfolioCategory = { 'ai' : null } |
  { 'web' : null } |
  { 'saas' : null } |
  { 'blockchain' : null } |
  { 'mobile' : null } |
  { 'branding' : null };
export interface PortfolioFilter {
  'status' : [] | [PublishStatus],
  'search' : [] | [string],
  'category' : [] | [PortfolioCategory],
}
export interface PortfolioProject {
  'id' : bigint,
  'galleryImages' : Array<ExternalBlob>,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'clientName' : string,
  'displayOrder' : bigint,
  'technologiesUsed' : Array<string>,
  'tags' : Array<string>,
  'createdDate' : [] | [bigint],
  'publishStatus' : PublishStatus,
  'description' : string,
  'results' : Array<string>,
  'linkedTestimonialId' : [] | [bigint],
  'category' : PortfolioCategory,
  'lastUpdatedDate' : [] | [bigint],
  'projectUrl' : [] | [string],
  'industry' : string,
}
export interface PortfolioProjectInput {
  'galleryImages' : Array<ExternalBlob>,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'clientName' : string,
  'displayOrder' : bigint,
  'technologiesUsed' : Array<string>,
  'tags' : Array<string>,
  'publishStatus' : PublishStatus,
  'description' : string,
  'results' : Array<string>,
  'linkedTestimonialId' : [] | [bigint],
  'category' : PortfolioCategory,
  'projectUrl' : [] | [string],
  'industry' : string,
}
export interface PortfolioProjectUpdate {
  'id' : bigint,
  'galleryImages' : Array<ExternalBlob>,
  'title' : string,
  'thumbnail' : [] | [ExternalBlob],
  'clientName' : string,
  'displayOrder' : bigint,
  'technologiesUsed' : Array<string>,
  'tags' : Array<string>,
  'publishStatus' : PublishStatus,
  'description' : string,
  'results' : Array<string>,
  'linkedTestimonialId' : [] | [bigint],
  'category' : PortfolioCategory,
  'projectUrl' : [] | [string],
  'industry' : string,
}
export type PublishStatus = { 'published' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export interface Service {
  'id' : bigint,
  'useCases' : Array<string>,
  'title' : string,
  'displayOrder' : bigint,
  'faqs' : Array<ServiceFaq>,
  'icon' : [] | [ExternalBlob],
  'createdDate' : [] | [bigint],
  'processSteps' : Array<ServiceProcessStep>,
  'targetAudience' : string,
  'shortDescription' : string,
  'isVisible' : boolean,
  'lastUpdatedDate' : [] | [bigint],
  'fullDescription' : string,
}
export interface ServiceFaq { 'question' : string, 'answer' : string }
export interface ServiceFilter {
  'search' : [] | [string],
  'isVisible' : [] | [boolean],
}
export interface ServiceInput {
  'useCases' : Array<string>,
  'title' : string,
  'displayOrder' : bigint,
  'faqs' : Array<ServiceFaq>,
  'icon' : [] | [ExternalBlob],
  'processSteps' : Array<ServiceProcessStep>,
  'targetAudience' : string,
  'shortDescription' : string,
  'isVisible' : boolean,
  'fullDescription' : string,
}
export interface ServiceProcessStep { 'step' : string, 'description' : string }
export interface ServiceUpdate {
  'id' : bigint,
  'useCases' : Array<string>,
  'title' : string,
  'displayOrder' : bigint,
  'faqs' : Array<ServiceFaq>,
  'icon' : [] | [ExternalBlob],
  'processSteps' : Array<ServiceProcessStep>,
  'targetAudience' : string,
  'shortDescription' : string,
  'isVisible' : boolean,
  'fullDescription' : string,
}
export interface Testimonial {
  'id' : bigint,
  'displayOrder' : bigint,
  'authorName' : string,
  'createdDate' : [] | [bigint],
  'quote' : string,
  'linkedPortfolioId' : [] | [bigint],
  'jobTitle' : string,
  'isVisible' : boolean,
  'companyName' : string,
  'lastUpdatedDate' : [] | [bigint],
  'rating' : bigint,
  'photo' : [] | [ExternalBlob],
}
export interface TestimonialFilter {
  'minRating' : [] | [bigint],
  'search' : [] | [string],
  'isVisible' : [] | [boolean],
  'maxRating' : [] | [bigint],
}
export interface TestimonialInput {
  'displayOrder' : bigint,
  'authorName' : string,
  'quote' : string,
  'linkedPortfolioId' : [] | [bigint],
  'jobTitle' : string,
  'isVisible' : boolean,
  'companyName' : string,
  'rating' : bigint,
  'photo' : [] | [ExternalBlob],
}
export interface TestimonialUpdate {
  'id' : bigint,
  'displayOrder' : bigint,
  'authorName' : string,
  'quote' : string,
  'linkedPortfolioId' : [] | [bigint],
  'jobTitle' : string,
  'isVisible' : boolean,
  'companyName' : string,
  'rating' : bigint,
  'photo' : [] | [ExternalBlob],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkDeletePortfolioProjects' : ActorMethod<[Array<bigint>], bigint>,
  'bulkDeleteServices' : ActorMethod<[Array<bigint>], bigint>,
  'bulkDeleteTestimonials' : ActorMethod<[Array<bigint>], bigint>,
  'bulkUpdatePortfolioStatus' : ActorMethod<
    [Array<bigint>, PublishStatus],
    bigint
  >,
  'bulkUpdateServiceVisibility' : ActorMethod<[Array<bigint>, boolean], bigint>,
  'bulkUpdateTestimonialVisibility' : ActorMethod<
    [Array<bigint>, boolean],
    bigint
  >,
  'createPortfolioProject' : ActorMethod<
    [PortfolioProjectInput],
    PortfolioProject
  >,
  'createService' : ActorMethod<[ServiceInput], Service>,
  'createTestimonial' : ActorMethod<[TestimonialInput], Testimonial>,
  'deletePortfolioProject' : ActorMethod<[bigint], boolean>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'deleteTestimonial' : ActorMethod<[bigint], boolean>,
  'exportData' : ActorMethod<[], ExportData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSettings' : ActorMethod<[], ContactSettings>,
  'getHomepageData' : ActorMethod<[], HomepageData>,
  'getPortfolioProject' : ActorMethod<[bigint], [] | [PortfolioProject]>,
  'getPortfolioProjects' : ActorMethod<
    [bigint, bigint, [] | [PortfolioFilter]],
    PaginatedPortfolioProjects
  >,
  'getPreviousContactSettings' : ActorMethod<[], [] | [ContactSettings]>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getServices' : ActorMethod<
    [bigint, bigint, [] | [ServiceFilter]],
    PaginatedServices
  >,
  'getTestimonial' : ActorMethod<[bigint], [] | [Testimonial]>,
  'getTestimonials' : ActorMethod<
    [bigint, bigint, [] | [TestimonialFilter]],
    PaginatedTestimonials
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importData' : ActorMethod<[ExportData, ImportOptions], ImportResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderPortfolioProjects' : ActorMethod<[Array<bigint>], boolean>,
  'reorderServices' : ActorMethod<[Array<bigint>], boolean>,
  'reorderTestimonials' : ActorMethod<[Array<bigint>], boolean>,
  'resetContactSettings' : ActorMethod<[], ContactSettings>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContactSettings' : ActorMethod<[ContactSettings], ContactSettings>,
  'updatePortfolioProject' : ActorMethod<
    [PortfolioProjectUpdate],
    [] | [PortfolioProject]
  >,
  'updateService' : ActorMethod<[ServiceUpdate], [] | [Service]>,
  'updateTestimonial' : ActorMethod<[TestimonialUpdate], [] | [Testimonial]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];